# Generated by Django 5.1.4 on 2024-12-27 23:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="note",
            old_name="bode",
            new_name="body",
        ),
    ]
