# Generated by Django 5.1.4 on 2024-12-28 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_user_options_rename_bode_note_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-id"]},
        ),
    ]
