# Generated by Django 5.1.4 on 2025-04-21 21:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_register"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Note",
        ),
    ]
