# Generated by Django 5.1.4 on 2025-04-21 21:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_delete_note"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
