# Generated by Django 5.1.4 on 2025-04-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="api/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.DeleteModel(
            name="image",
        ),
    ]
