# Generated by Django 5.1.4 on 2025-04-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_photo_delete_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namefood", models.CharField(max_length=100)),
                ("nutrationinformation", models.TextField()),
                ("health", models.TextField()),
                ("recipy", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
