# Generated by Django 5.1.4 on 2025-04-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_food_options_remove_food_nutrationinformation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="Nutrition_info",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="food",
            name="health",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="food",
            name="recipy",
            field=models.TextField(default=""),
        ),
    ]
