# Generated by Django 5.1.4 on 2025-04-28 19:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_food_nutrition_info_alter_food_health_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="Nutrition_info",
        ),
    ]
