# Generated by Django 5.1.4 on 2025-04-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_remove_food_nutrition_info"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="food",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="food",
            name="Calories",
        ),
        migrations.RemoveField(
            model_name="food",
            name="Carbohydrates",
        ),
        migrations.RemoveField(
            model_name="food",
            name="Dietary_Fiber",
        ),
        migrations.RemoveField(
            model_name="food",
            name="Fat",
        ),
        migrations.RemoveField(
            model_name="food",
            name="Potassium",
        ),
        migrations.RemoveField(
            model_name="food",
            name="Protein",
        ),
        migrations.RemoveField(
            model_name="food",
            name="Sodium",
        ),
        migrations.RemoveField(
            model_name="food",
            name="Sugars",
        ),
        migrations.AddField(
            model_name="food",
            name="nutrationinformation",
            field=models.TextField(default=""),
        ),
    ]
