# Generated by Django 5.1.4 on 2025-04-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_food_options_remove_food_calories_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="food",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveField(
            model_name="food",
            name="nutrationinformation",
        ),
        migrations.AddField(
            model_name="food",
            name="Calories",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="food",
            name="Carbohydrates",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="food",
            name="Dietary_Fiber",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="food",
            name="Fat",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="food",
            name="Potassium",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="food",
            name="Protein",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="food",
            name="Sodium",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="food",
            name="Sugars",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
