# Generated by Django 5.1.4 on 2025-04-28 20:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_alter_food_options_remove_food_nutrationinformation_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="food",
            options={"ordering": ["-created_at"]},
        ),
    ]
