# Generated by Django 5.1.4 on 2025-05-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_alter_food_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.TextField()),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Food1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namefood", models.CharField(max_length=100)),
                ("nut_info", models.TextField(default="")),
                ("health", models.TextField(default="")),
                ("recipy", models.TextField(default="")),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="food",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="photo",
            name="uploaded_at",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="register",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
