# Generated by Django 5.1.4 on 2025-05-29 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_chat_food1_alter_food_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="message",
        ),
        migrations.AddField(
            model_name="chat",
            name="botmessage",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="chat",
            name="usermessage",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="food1",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="food1",
                to="api.register",
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to="api.register",
            ),
        ),
    ]
