# Generated by Django 5.1.4 on 2025-06-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_remove_chat_message_chat_botmessage_chat_usermessage_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="food",
        ),
        migrations.DeleteModel(
            name="Photo",
        ),
        migrations.RenameField(
            model_name="chat",
            old_name="user",
            new_name="user_id",
        ),
        migrations.RenameField(
            model_name="food1",
            old_name="user",
            new_name="user_id",
        ),
        migrations.AddField(
            model_name="register",
            name="disease",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="register",
            name="height",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="register",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
